# Generated by Django 5.1.1 on 2024-11-11 17:26

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('url', models.URLField()),
                ('title', models.CharField(default='Untitled', max_length=256)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('subtitle', models.TextField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('generator', 'generator'), ('builder', 'builder')], max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
