# Generated by Django 5.1.1 on 2025-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsschannel',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
