# Generated by Django 5.1.1 on 2025-04-15 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('site_id', models.TextField()),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('image', models.URLField(null=True)),
                ('summary', models.TextField(null=True)),
                ('author', models.CharField(max_length=256, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.articlecollection')),
            ],
        ),
    ]
